spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: cloudinary
#file:
#  upload-dir: ${FILE_UPLOAD_DIR}
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT}